@startuml Logged User Actions 0
scale 1
left to right direction
:Usuário (logado): as User
User --> (Registrar-se)
User --> (Login)
User --> (Login Google)
User --> (Login Facebook)
User --> (Logout)
User --> (Encerrar Conta)
User --> (Criar "cadernos")
User --> (Editar "cadernos")
User --> (Criar sala pública)
User --> (Criar sala privada)
User --> (Entrar em sala)
User --> (Visualizar salas)
User --> (Sair da sala)
@enduml
